build:
	g++ -std=c++11 -o ./project2.out src/main.cpp src/File.cpp
tasks:
	g++ -std=c++11 -o ./project2.out src/main.cpp src/File.cpp
	./project2.out output/part11.tga input/layer1.tga multiply input/circles.tga
	./project2.out output/part12.tga input/layer1.tga flip
	./project2.out output/part13.tga input/layer2.tga subtract input/layer1.tga